CREATE TABLESPACE TB_NAME_IDX DATAFILE 'DATA_PATH/TB_FILE_IDX.dbf' SIZE 100m AUTOEXTEND ON NEXT 32m EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE TB_NAME DATAFILE 'DATA_PATH/TB_FILE.dbf' SIZE 100m AUTOEXTEND ON NEXT 32m EXTENT MANAGEMENT LOCAL;

CREATE TEMPORARY TABLESPACE TB_NAME_TEMP TEMPFILE 'DATA_PATH/TB_FILE_TEMP.dbf' SIZE 100m AUTOEXTEND ON NEXT 32m EXTENT MANAGEMENT LOCAL;

CREATE USER TEST IDENTIFIED BY PASSWORD DEFAULT TABLESPACE TB_NAME TEMPORARY TABLESPACE TB_NAME_TEMP;

GRANT CONNECT, RESOURCE, DBA, EXPORT FULL DATABASE, IMPORT FULL DATABASE TO TEST;

--DROP USER TEST;
--DROP TABLESPACE TB_NAME_IDX INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE TB_NAME INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE TB_NAME_TEMP INCLUDING CONTENTS AND DATAFILES;

--//////////////////////////////////////
-- USER SQL
CREATE USER TEST IDENTIFIED BY 123456 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- ROLES
GRANT "RESOURCE" TO TEST ;
GRANT "CONNECT" TO TEST ;
ALTER USER TEST DEFAULT ROLE "RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE SEQUENCE TO TEST ;
GRANT CREATE SYNONYM TO TEST ;
GRANT CREATE VIEW TO TEST ;
GRANT CREATE SESSION TO TEST ;
GRANT UNLIMITED TABLESPACE TO TEST ;
GRANT CREATE DATABASE LINK TO TEST ;
GRANT ALTER SESSION TO TEST ;
--//////////////////////////////////////

--exp HR/123456 owner=HR file=hr.dmp
--imp TEST/123456 fromuser=HR touser=TEST file=hr.dmp